export class Countries
{
    public static countries = [
        {"country":"Afghanistan","cid":1}, {"country":"Albania","cid":2}, {"country":"Algeria","cid":3}, 
        {"country":"American Samoa","cid":4}, {"country":"Andorra","cid":5}, {"country":"Angola","cid":6}, 
        {"country":"Anguilla","cid":7}, {"country":"Antarctica","cid":8}, {"country":"Antigua and Barbuda","cid":9}, 
        {"country":"Argentina","cid":10}, {"country":"Armenia","cid":11}, {"country":"Aruba","cid":12}, 
        {"country":"Australia","cid":13}, {"country":"Austria","cid":14}, {"country":"Azerbaijan","cid":15}, 
        {"country":"Bahamas","cid":16}, {"country":"Bahrain","cid":17}, {"country":"Bangladesh","cid":18}, 
        {"country":"Barbados","cid":19}, {"country":"Belarus","cid":20}, {"country":"Belgium","cid":21}, 
        {"country":"Belize","cid":22}, {"country":"Benin","cid":23}, {"country":"Bermuda","cid":24}, 
        {"country":"Bhutan","cid":25}, {"country":"Bolivia","cid":26}, 
        {"country":"Bosnia and Herzegovina","cid":27}, {"country":"Botswana","cid":28}, 
        {"country":"Bouvet Island","cid":29}, {"country":"Brazil","cid":30}, 
        {"country":"British Indian Ocean Territory","cid":31}, {"country":"Brunei Darussalam","cid":32}, 
        {"country":"Bulgaria","cid":33}, {"country":"Burkina Faso","cid":34}, {"country":"Burundi","cid":35}, 
        {"country":"Cambodia","cid":36}, {"country":"Cameroon","cid":37}, {"country":"Canada","cid":38}, 
        {"country":"Cape Verde","cid":39}, {"country":"Cayman Islands","cid":40},
        {"country":"Central African Republic","cid":41}, {"country":"Chad","cid":42}, 
        {"country":"Chile","cid":43}, {"country":"China","cid":44}, {"country":"Christmas Island","cid":45}, 
        {"country":"Cocos (Keeling) Islands","cid":46}, {"country":"Colombia","cid":47}, 
        {"country":"Comoros","cid":48}, {"country":"Congo","cid":49},
        {"country":"Congo, the Democratic Republic of the","cid":50}, {"country":"Cook Islands","cid":51}, 
        {"country":"Costa Rica","cid":52}, {"country":"Cote D'Ivoire","cid":53}, {"country":"Croatia","cid":54},
        {"country":"Cuba","cid":55}, {"country":"Cyprus","cid":56}, {"country":"Czech Republic","cid":57}, 
        {"country":"Denmark","cid":58}, {"country":"Djibouti","cid":59}, {"country":"Dominica","cid":60}, 
        {"country":"Dominican Republic","cid":61}, {"country":"Ecuador","cid":62}, {"country":"Egypt","cid":63},
        {"country":"El Salvador","cid":64}, {"country":"Equatorial Guinea","cid":65}, {"country":"Eritrea","cid":66},
        {"country":"Estonia","cid":67}, {"country":"Ethiopia","cid":68}, 
        {"country":"Falkland Islands (Malvinas)","cid":69}, {"country":"Faroe Islands","cid":70}, 
        {"country":"Fiji","cid":71}, {"country":"Finland","cid":72}, {"country":"France","cid":73}, 
        {"country":"French Guiana","cid":74}, {"country":"French Polynesia","cid":75}, 
        {"country":"French Southern Territories","cid":76}, {"country":"Gabon","cid":77}, 
        {"country":"Gambia","cid":78}, {"country":"Georgia","cid":79}, {"country":"Germany","cid":80}, 
        {"country":"Ghana","cid":81}, {"country":"Gibraltar","cid":82}, {"country":"Greece","cid":83}, 
        {"country":"Greenland","cid":84}, {"country":"Grenada","cid":85}, {"country":"Guadeloupe","cid":86}, 
        {"country":"Guam","cid":87}, {"country":"Guatemala","cid":88}, {"country":"Guinea-Bissau","cid":89}, 
        {"country":"Guyana","cid":90}, {"country":"Haiti","cid":91}, 
        {"country":"Heard Island and Mcdonald Islands","cid":92}, 
        {"country":"Holy See (Vatican City State)","cid":93}, {"country":"Honduras","cid":94}, 
        {"country":"Hong Kong","cid":95}, {"country":"Hungary","cid":96}, {"country":"Iceland","cid":97}, 
        {"country":"India","cid":98}, {"country":"Indonesia","cid":99}, 
        {"country":"Iran, Islamic Republic of","cid":100}, {"country":"Iraq","cid":101}, 
        {"country":"Ireland","cid":102}, {"country":"Israel","cid":103}, {"country":"Italy","cid":104}, 
        {"country":"Jamaica","cid":105}, {"country":"Japan","cid":106}, {"country":"Jordan","cid":107}, 
        {"country":"Kazakhstan","cid":108}, {"country":"Kenya","cid":109}, {"country":"Kiribati","cid":110}, 
        {"country":"Korea, Democratic People's Republic of","cid":111}, {"country":"Korea, Republic of","cid":112}, 
        {"country":"Kuwait","cid":113}, {"country":"Kyrgyzstan","cid":114}, 
        {"country":"Lao People's Democratic Republic","cid":115}, {"country":"Latvia","cid":116}, 
        {"country":"Lebanon","cid":117}, {"country":"Lesotho","cid":118}, {"country":"Liberia","cid":119}, 
        {"country":"Libyan Arab Jamahiriya","cid":120}, {"country":"Liechtenstein","cid":121}, 
        {"country":"Lithuania","cid":122}, {"country":"Luxembourg","cid":123}, {"country":"Macao","cid":124}, 
        {"country":"Macedonia","cid":125}, {"country":"Madagascar","cid":126}, {"country":"Malawi","cid":127}, 
        {"country":"Malaysia","cid":128}, {"country":"Maldives","cid":129}, {"country":"Mali","cid":130}, 
        {"country":"Malta","cid":131}, {"country":"Marshall Islands","cid":132}, {"country":"Martinique","cid":133}, 
        {"country":"Mauritania","cid":134}, {"country":"Mauritius","cid":135}, {"country":"Mayotte","cid":136}, 
        {"country":"Mexico","cid":137}, {"country":"Micronesia, Federated States of","cid":138}, 
        {"country":"Moldova","cid":139}, {"country":"Monaco","cid":140}, {"country":"Mongolia","cid":141}, 
        {"country":"Montenegro","cid":142}, {"country":"Montserrat","cid":143}, {"country":"Morocco","cid":144}, 
        {"country":"Mozambique","cid":145}, {"country":"Myanmar","cid":146}, {"country":"Namibia","cid":147}, 
        {"country":"Nauru","cid":148}, {"country":"Nepal","cid":149}, {"country":"Netherlands","cid":150}, 
        {"country":"Netherlands Antilles","cid":151}, {"country":"New Caledonia","cid":152}, 
        {"country":"New Zealand","cid":153}, {"country":"Nicaragua","cid":154}, {"country":"Niger","cid":155}, 
        {"country":"Nigeria","cid":156}, {"country":"Niue","cid":157}, {"country":"Norfolk Island","cid":158}, 
        {"country":"Northern Mariana Islands","cid":159}, {"country":"Norway","cid":160}, 
        {"country":"Oman","cid":161}, {"country":"Pakistan","cid":162}, {"country":"Palau","cid":163}, 
        {"country":"Palestinian Territory, Occupied","cid":164}, {"country":"Panama","cid":165}, 
        {"country":"Papua New Guinea","cid":166}, {"country":"Paraguay","cid":167}, {"country":"Peru","cid":168}, 
        {"country":"Philippines","cid":169}, {"country":"Pitcairn","cid":170}, {"country":"Poland","cid":171}, 
        {"country":"Portugal","cid":172}, {"country":"Puerto Rico","cid":173}, {"country":"Qatar","cid":174}, 
        {"country":"Reunion","cid":175}, {"country":"Romania","cid":176}, {"country":"Russian Federation","cid":177}, 
        {"country":"Rwanda","cid":178}, {"country":"Saint Helena","cid":179}, 
        {"country":"Saint Kitts and Nevis","cid":180}, {"country":"Saint Lucia","cid":181}, 
        {"country":"Saint Pierre and Miquelon","cid":182}, {"country":"Saint Vincent and the Grenadines","cid":183}, 
        {"country":"Samoa","cid":184}, {"country":"San Marino","cid":185}, 
        {"country":"Sao Tome and Principe","cid":186}, {"country":"Saudi Arabia","cid":187}, 
        {"country":"Senegal","cid":188}, {"country":"Serbia","cid":189}, {"country":"Seychelles","cid":190}, 
        {"country":"Sierra Leone","cid":191}, {"country":"Singapore","cid":192}, {"country":"Slovakia","cid":193}, 
        {"country":"Slovenia","cid":194}, {"country":"Solomon Islands","cid":195}, {"country":"Somalia","cid":196}, 
        {"country":"South Africa","cid":197}, {"country":"South Georgia and the South Sandwich Islands","cid":198}, 
        {"country":"Spain","cid":199}, {"country":"Sri Lanka","cid":200}, {"country":"Sudan","cid":201}, 
        {"country":"Suriname","cid":202}, {"country":"Svalbard and Jan Mayen","cid":203}, 
        {"country":"Swaziland","cid":204}, {"country":"Sweden","cid":205}, {"country":"Switzerland","cid":206}, 
        {"country":"Syrian Arab Republic","cid":207}, {"country":"Taiwan","cid":208}, 
        {"country":"Tajikistan","cid":209}, {"country":"Tanzania, United Republic of","cid":210}, 
        {"country":"Thailand","cid":211}, {"country":"Timor-Leste","cid":212}, {"country":"Togo","cid":213}, 
        {"country":"Tokelau","cid":214}, {"country":"Tonga","cid":215}, {"country":"Trinidad and Tobago","cid":216}, 
        {"country":"Tunisia","cid":217}, {"country":"Turkey","cid":218}, {"country":"Turkmenistan","cid":219}, 
        {"country":"Turks and Caicos Islands","cid":220}, {"country":"Tuvalu","cid":221}, 
        {"country":"Uganda","cid":222}, {"country":"Ukraine","cid":223}, 
        {"country":"United Arab Emirates","cid":224}, {"country":"United Kingdom","cid":225}, 
        {"country":"United States","cid":226}, {"country":"United States Minor Outlying Islands","cid":227}, 
        {"country":"Uruguay","cid":228}, {"country":"Uzbekistan","cid":229}, {"country":"Vanuatu","cid":230}, 
        {"country":"Venezuela","cid":231}, {"country":"Viet Nam","cid":232}, 
        {"country":"Virgin Islands, British","cid":233}, {"country":"Virgin Islands, U.s.","cid":234}, 
        {"country":"Wallis and Futuna","cid":235}, {"country":"Western Sahara","cid":236}, 
        {"country":"Yemen","cid":237}, {"country":"Zambia","cid":238}, {"country":"Zimbabwe","cid":239}
        ]
}